apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: training-divyesh-poi-map-app-dev
  annotations:
    argocd/app-name: training-divyesh-poi-map-app-dev
    backstage.io/kubernetes-id: training-divyesh-poi-map-app
    backstage.io/kubernetes-namespace: training-divyesh
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/training-divyesh-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/training-divyesh/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/training-divyesh/deployments/training-divyesh-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/training-divyesh-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://training-divyesh-poi-map-app-training-divyesh.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-training-divyesh
  consumesApis:
    - gateway-api-training-divyesh
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-training-divyesh
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
